spring:
  application:
    name:
      event-service
  liquibase:
    change-log:
      liquibase/changelog.yaml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080

